# Generated by Django 4.2 on 2023-12-18 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(
                help_text='пользователь, который дал ответ',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_answers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='task',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='image',
                to='events.task',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_task',
                to='events.event',
                verbose_name='мероприятие',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_tags',
                to='events.task',
                verbose_name='тэги задания',
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='events.event',
                verbose_name='пост',
            ),
        ),
        migrations.AddField(
            model_name='eventresults',
            name='event',
            field=models.ForeignKey(
                help_text='мероприятие, к которому относится результат',
                on_delete=django.db.models.deletion.CASCADE,
                to='events.event',
                verbose_name='мероприятие',
            ),
        ),
        migrations.AddField(
            model_name='eventresults',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, участвовавший в мероприятии',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
        migrations.AddField(
            model_name='eventmainimage',
            name='event',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                to='events.event',
            ),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gallery',
                to='events.event',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(
                help_text='Организатор мероприятия',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_author',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='events.category',
                verbose_name='категория',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='events.post',
                verbose_name='комментарии',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                help_text='пользователь, который оставил комментарий',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_commentor',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
        migrations.AddField(
            model_name='answerimage',
            name='answer',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='image',
                to='events.answer',
            ),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='answers',
                to='events.task',
                verbose_name='задание',
            ),
        ),
    ]
