# Generated by Django 4.2 on 2023-05-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventresults_is_ended_alter_answer_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.answer",
            ),
        ),
    ]
