# Generated by Django 4.2 on 2023-12-18 20:32

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimage',
            name='task',
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to=events.models.answer_directiry_path,
                verbose_name='изображение',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to=events.models.task_directiry_path,
                verbose_name='изображение',
            ),
        ),
        migrations.DeleteModel(
            name='AnswerImage',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
