# Generated by Django 4.2 on 2023-12-18 20:35

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    dependencies = [
        (
            'events',
            '0003_remove_taskimage_task_answer_image_task_image_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to=events.models.event_directiry_path,
                verbose_name='изображение',
            ),
        ),
    ]
