# Generated by Django 4.2 on 2023-12-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresults',
            name='is_ended',
        ),
        migrations.AlterField(
            model_name='eventresults',
            name='number_of_points',
            field=models.PositiveIntegerField(
                default=0, verbose_name='количество набранных баллов'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(
                choices=[
                    (0, 'тестовое задание'),
                    (1, 'письменное задание'),
                    (2, 'файловое задание'),
                ],
                default=0,
                verbose_name='тип задания',
            ),
        ),
    ]
