# Generated by Django 4.2 on 2023-12-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_remove_eventresults_is_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresults',
            name='is_ended',
            field=models.BooleanField(
                default=False,
                help_text='Завершено ли мероприятие?',
                verbose_name='завершено',
            ),
        ),
    ]
