# Generated by Django 4.2 on 2023-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0007_event_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresults',
            name='is_correct_secret_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='secret_key',
            field=models.CharField(
                default='IA~.\nl=\nUJ[>\x0cco,akN6', max_length=20, unique=True
            ),
        ),
    ]
