# Generated by Django 4.2 on 2023-12-18 19:22

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название новости',
                        max_length=150,
                        verbose_name='новость',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Введите текст новости',
                        verbose_name='текст новости',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=homepage.models.generate_image_path,
                        verbose_name='фото',
                    ),
                ),
                (
                    'time',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='время публикации'
                    ),
                ),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
