# Generated by Django 4.2 on 2023-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_new_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="время публикации"
            ),
        ),
    ]
